---
driver:
  name: docker

platforms:
  - name: amazonlinux2
    image: geerlingguy/docker-amazonlinux2-ansible:latest
    build:
      context: .
      dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
  options:
    vvv: true
