---
driver:
  name: docker

platforms:
  - name: amazonlinux2
    image: amazonlinux:2
    build:
      context: .
      dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init

provisioner:
  name: ansible
  options:
    vvv: true
