name: Run Ansible Playbook for Jenkins

on:
  push:
    paths:
      - "install.yml"

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook install.yml \
            -i "${{ secrets.EC2_HOST }}," \
            -u ec2-user \
            --ssh-extra-args "-o StrictHostKeyChecking=no"
