name: Scheduled Backup

on:
  schedule:
    # Runs every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:  # allows manual trigger too

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change to your region

      - name: Create Backup Archive
        run: |
          mkdir -p backup
          tar -czf backup/myapp-$(date +%F-%H-%M).tar.gz .

      - name: Upload to S3
        run: |
          aws s3 cp backup/ s3://your-s3-bucket-name/backups/ --recursive
